apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "python-app-%s"  .Values.color }}
  namespace: {{ printf "%s-%s" .Values.name .Values.environment }}
  labels:
    class: {{ .Values.class }}
    environment: {{ .Values.environment }}
    region: {{ .Values.region }}
spec:
  selector:
    matchLabels:
      app: {{ printf "python-app-%s" .Values.color }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ printf "python-app-%s" .Values.color }}
        class: {{ .Values.class }}
        environment: {{ .Values.environment }}
        region: {{ .Values.region }}
        version: {{ .Values.version }}
    spec:
      containers:
        - name: {{ printf "python-app-%s" .Values.color }}
          image: {{ printf "tatroc/private:%s" .Values.image_tag }}
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 5000
              protocol: TCP
          resources:
            limits:
              cpu: 1
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 50Mi
      imagePullSecrets:
        - name: {{ .Values.pull_secret_name }}