apiVersion: v1
kind: Namespace
metadata:
  #name: "{{ .Values.name }}:-:{{ .Values.environment }}"
  name: {{ printf "%s-%s" .Values.name .Values.environment }}
  labels:
    app: {{ printf "python-app-%s" .Values.color }}
    class: {{ .Values.class }}
    environment: {{ .Values.environment }}
    region: {{ .Values.region }}