apiVersion: v1
kind: Namespace
metadata:
  name: "{{ .Values.name }}:-:{{ .Values.environment }}"
  labels:
    app: python-app-{{ .Values.color }}
    class: {{ .Values.class }}
    environment: {{ .Values.environment }}
    region: {{ .Values.region }}