apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.docker_hub_secret }}
kind: Secret
metadata:
  name: {{ .Values.pull_secret_name }}
  namespace: {{ printf "%s-%s" .Values.name .Values.environment }}
type: kubernetes.io/dockerconfigjson