apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.docker_hub_secret }}
kind: Secret
metadata:
  name: {{ .Values.pull_secret_name }}
  namespace: {{ .Values.name }}-{{ .Values.environment }}
type: kubernetes.io/dockerconfigjson