---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "python-app-service-%s" .Values.color }}
  namespace: {{ printf "%s-%s" .Values.name .Values.environment }}
  labels:
    class: {{ .Values.class }}
    environment: {{ .Values.environment }}
    region: {{ .Values.region }}
spec:
  selector:
    app.kubernetes.io/name: {{ printf "python-app-%s" .Values.color }}
  ports:
  - name: {{ printf "python-app-%s" .Values.color }}
    protocol: TCP
    port: 80
    targetPort: 5000